# image will be published to ghcr.io/<user>/<name>
name: biber-os
# description will be included in the image's metadata
description: This is my personal OS image.

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/silverblue-main
image-version: 40 # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - source: system
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /
                       # put configuration files you want in /usr/etc/ inside the image
                       # while putting files in /etc/ is done on booted system by system administrators.
                       # read more about this in files module reference.

  - type: rpm-ostree
    repos:
      # - https://copr.fedorainfracloud.org/coprs/atim/starship/repo/fedora-%OS_VERSION%/atim-starship-fedora-%OS_VERSION%.repo
      - https://pkgs.tailscale.com/stable/fedora/tailscale.repo
    keys:
      - https://gitlab.com/paulcarroty/vscodium-deb-rpm-repo/-/raw/master/pub.gpg
    install:
      - nextcloud-client
      - stow
      - jq
      - tailscale
      - codium
      - hledger
    remove:
      - firefox
      - firefox-langpacks # also remove firefox dependency (not required for all packages, this is a special case)
      - nvtop
      - htop

  - type: default-flatpaks
    notify: true # Send notification after install/uninstall is finished (true/false)
    system:
      # If no repo information is specified, Flathub will be used by default
      # repo-url: https://dl.flathub.org/repo/flathub.flatpakrepo
      # repo-name: flathub
      # repo-title: "Flathub (system-wide)" # Optional; this sets the remote's user-facing name in graphical frontends like GNOME Software
      install:
        # browser
        - com.google.Chrome
        - org.mozilla.firefox

        # Social/Chat
        - com.discordapp.Discord
        - com.github.junrrein.PDFSlicer
        - org.mozilla.Thunderbird
        - dev.geopjr.Tuba

        # media
        - org.gnome.Loupe
        - com.github.neithern.g4music
        - com.github.rafostar.Clapper
        - org.gnome.Podcasts
        - org.gimp.GIMP
        - org.inkscape.Inkscape
        - org.nickvision.tubeconverter
        - org.nickvision.tagger

        # Games
        - org.gnome.Mines
        - com.mojang.Minecraft
        - org.gnome.Aisleriot

        # Documents
        - org.gnome.TextEditor
        - org.gnome.World.Iotas
        - org.gnome.gitlab.somas.Apostrophe
        - com.github.johnfactotum.Foliate
        - org.gustavoperedo.FontDownloader
        - garden.jamie.Morphosis
        - org.gnome.Papers

        # System
        - com.github.tchx84.Flatseal
        - com.mattjakeman.ExtensionManager
        - app.devsuite.Ptyxis

      remove:
      # - org.gnome.eog
  
  - type: gnome-extensions
    install:
      - Just Perfection
      - Dash to Dock

  - type: fonts
    fonts:
      google-fonts:
        - Inter

  - type: gschema-overrides
    include:
      - zz-biber-os.gschema.override


  - type: signing # this sets up the proper policy & signing files for signed images to work fully
