# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json

name: biber-os
description: This is my personal OS image.

base-image: quay.io/fedora-ostree-desktops/silverblue
image-version: 41

modules:
  - type: files
    files: [{ source: system, destination: / }]

  - type: rpm-ostree
    repos:
      - https://pkgs.tailscale.com/stable/fedora/tailscale.repo
    remove:
      - firefox
      - firefox-langpacks # also remove firefox dependency (not required for all packages, this is a special case)
      - toolbox
    install:
      - stow
      - jq
      - distrobox
      - tailscale
      - hledger
      - hledger-ui
      - nextcloud-client
      - fastfetch

  - type: default-flatpaks
    notify: true
    system:
      install:
        # browser
        - com.google.Chrome
        - org.mozilla.firefox
        - org.gnome.Web

        # Social/Chat
        - com.discordapp.Discord
        - org.gnome.Fractal
        - com.github.junrrein.PDFSlicer
        - org.mozilla.Thunderbird
        - dev.geopjr.Tuba

        # GNOME basics that are missing for some reason
        - org.gnome.font-viewer
        - org.gnome.FileRoller
        - org.gnome.Loupe
        - org.gnome.NautilusPreviewer
        - org.gnome.Characters

        # media
        - com.github.neithern.g4music
        - com.github.rafostar.Clapper
        - org.gnome.Podcasts
        - org.gimp.GIMP
        - org.inkscape.Inkscape
        - org.nickvision.tubeconverter
        - org.nickvision.tagger
        - org.gnome.Snapshot

        # Games
        - org.gnome.Mines
        - org.gnome.Chess
        - org.gnome.Aisleriot
        - com.mojang.Minecraft

        # Documents
        - org.gnome.TextEditor
        - org.gnome.World.Iotas
        - org.gnome.gitlab.somas.Apostrophe
        - com.github.johnfactotum.Foliate
        - garden.jamie.Morphosis
        - org.gnome.Papers
        - org.onlyoffice.desktopeditors

        # System
        - com.github.tchx84.Flatseal
        - com.mattjakeman.ExtensionManager

      remove: []

  - type: signing # this sets up the proper policy & signing files for signed images to work fully
